name: Admin API CI

on:
  push:
    branches:
      - patch-cicd-demo
    paths:
      - 'Demo-Patch-CICD/src/AdminAPI/**'
#new line
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore Demo-Patch-CICD/src/AdminAPI/AdminAPI.csproj

      - name: Build
        run: dotnet build Demo-Patch-CICD/src/AdminAPI/AdminAPI.csproj --configuration Release --no-restore

      - name: Publish
        run: dotnet publish Demo-Patch-CICD/src/AdminAPI/AdminAPI.csproj -c Release -o publish/AdminAPI

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AdminAPI
          path: publish/AdminAPI