name: Release Admin API

on:
  workflow_dispatch:
    inputs:
      sprint:
        description: "Sprint Number"
        required: true
        default: "73"

      patch:
        description: "Patch Number"
        required: true
        default: "01"

jobs:

  deploy_rc:
    name: Deploy to RC
    runs-on: ubuntu-latest

    environment:
      name: RC

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: Admin_Sprint${{ github.event.inputs.sprint }}_Patch${{ github.event.inputs.patch }}
          path: deploy

      - name: Show Downloaded Files
        run: ls -R deploy

      - name: Create RC Folder
        run: mkdir -p Demo-Patch-CICD/environments/RC

      - name: Deploy to RC
        run: cp -R deploy/. Demo-Patch-CICD/environments/RC/


  deploy_cluster01:
    name: Deploy to Cluster01
    needs: deploy_rc
    runs-on: ubuntu-latest

    environment:
      name: Cluster01

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: Admin_Sprint${{ github.event.inputs.sprint }}_Patch${{ github.event.inputs.patch }}
          path: deploy

      - name: Show Downloaded Files
        run: ls -R deploy

      - name: Create Cluster01 Folder
        run: mkdir -p Demo-Patch-CICD/environments/Cluster01

      - name: Deploy to Cluster01
        run: cp -R deploy/. Demo-Patch-CICD/environments/Cluster01/
  


    deploy_cluster02:
    name: Deploy to Cluster02
    needs: deploy_cluster01
    runs-on: ubuntu-latest

    environment:
      name: Cluster02

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: Admin_Sprint${{ github.event.inputs.sprint }}_Patch${{ github.event.inputs.patch }}
          path: deploy

      - name: Create Cluster02 Folder
        run: mkdir -p Demo-Patch-CICD/environments/Cluster02

      - name: Deploy to Cluster02
        run: cp -R deploy/. Demo-Patch-CICD/environments/Cluster02/


    deploy_cluster03:
    name: Deploy to Cluster03
    needs: deploy_cluster02
    runs-on: ubuntu-latest

    environment:
      name: Cluster03

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: Admin_Sprint${{ github.event.inputs.sprint }}_Patch${{ github.event.inputs.patch }}
          path: deploy

      - name: Create Cluster03 Folder
        run: mkdir -p Demo-Patch-CICD/environments/Cluster03

      - name: Deploy to Cluster03
        run: cp -R deploy/. Demo-Patch-CICD/environments/Cluster03/